### ISSUE TITLE
Horizontal scrollbar

### ISSUE THREAD

**Issue by lukawski** [arthow4n/fcc-voting#3]
I don't know whether it is intentional but a horizontal scrollbar is visible. You can scroll far to the right and find completely empty space. It doesn't look well and I couldn't find any good use for this.

**Comment by arthow4n** [comment]
Hi @lukawski,
I didn't see one in my environment, which browser environment are you using? Screenshots would be appreciated.

**Comment by lukawski** [comment]
I'm using Chrome version 56.0.2924.87. Apparently it's present only at home page. My resolution is 1366x768.
![fcc-polling-1](https://cloud.githubusercontent.com/assets/15970299/23126921/4171daa0-f779-11e6-9079-68b2d9ab9ca2.png)
![fcc-poll-2](https://cloud.githubusercontent.com/assets/15970299/23126920/41698800-f779-11e6-9c46-5afe3795cd9e.png)

**Comment by arthow4n** [comment]
Thanks for the screenshot! I have reproduced the bug, will fix this later. 
An `overflow-x: hidden;` on `<body>` should work.

**Comment by arthow4n** [comment]
Fixed in 1f6b58c.
Changes pushed to running heroku instance (fcc-voting-arthow4n).
