### ISSUE TITLE
Issue with XSS. 

### ISSUE THREAD

**Issue by MiloATH** [arthow4n/fcc-voting#4]
Scripts can be submitted as options to a poll. The scripts run when the chart legend is generated. See: https://fcc-voting-arthow4n.herokuapp.com/polls/o5wuyhgRXPBgLMxdf

**Comment by arthow4n** [comment]
Hi @MiloATH, thanks for reporting!
Did some dirty hotfix in e0d8a4b and updated running heroku instance ( https://fcc-voting-arthow4n.herokuapp.com/ ).
Currently this hotfix breaks the chart when `&`,`<`,`>` is contained in the option (#5).
